language: ruby
rvm:
    - 2.2.4

install: 
    - bundle install

script:
    - bundle exec jekyll build

after_success:
    - "if [[ $TRAVIS_BRANCH == master ]]; then echo \"This is going to be deployed.\"; fi"
