language: ruby
rvm:
    - 2.2.4

install: 
    - bundle install
    - npm install -g bower
    - bower install -p

script:
    - bundle exec jekyll build

after_success:
    - "if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = master ]; then ./deploy-from-travis.sh; fi"
